apiVersion: v1
kind: Pod
metadata:
  name: john-kafka-python-new-topic
  namespace: wds-k8s-dev
spec:
  containers:
  - image: us.icr.io/git-defenders/john-kafka-python-console-sample:latest
    imagePullPolicy: IfNotPresent
    name: python-sample
    env:
    - name: VCAP_SERVICES
      valueFrom:
          secretKeyRef:
            name: eventstreams-binding
            key: binding
  imagePullSecrets: 
    - name: wds-k8s-dev-us-icr-io